baseURL: "https://caioferreira.dev/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Simple Made Daily
paginate: 5
theme: github.com/adityatelange/hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Blog
                  url: posts/
                  weight: 1
                - name: Search
                  url: search/
                  weight: 5
                - name: Tags
                  url: tags/
                  weight: 5

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: ""
    author: Caio Ferreira

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    disableScrollToTop: true
    displayFullLangName: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    ShareButtons:
    - twitter
    - linkedin
    - reddit


    profileMode:
        enabled: true
        title: Caio Ferreira
        subtitle: |
            I'm a software engineer passionate about unique puzzles and improving others developers' life.
            
            Do not believe in the *daily*, I write whenever I can.
        

            Security **|** Golang **|** Kubernetes **|** Architecture
        imageUrl: "images/self.png"
        imageTitle: self
        imageWidth: 300
        imageHeight: 300

    socialIcons:
        - name: github
          url: "https://github.com/caiorcferreira"
        - name: linkedin
          url: "https://www.linkedin.com/in/caiorcferreira/"
        - name: Rss
          url: "index.xml"

    editPost:
        URL: "https://github.com/caiorcferreira/caioferreira.dev/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    label:
        text: Simple Made Daily
        icon: logo.png
        iconHeight: 28
        iconWidth: 28

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
        favicon: "favicon.png"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true